# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'virtualBookmark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'UICircularProgressRing'
  pod 'RealmSwift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Fabric'
  pod 'Crashlytics'

  # Pods for virtualBookmark

  target 'virtualBookmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'virtualBookmarkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
