# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'troiswresto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for troiswresto
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'Firebase/Auth'
  pod 'FacebookCore'
  pod 'FacebookLogin'

  target 'troiswrestoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'Firebase/Auth'
    pod 'FacebookCore'
    pod 'FacebookLogin'
  end

  target 'troiswrestoUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'Firebase/Auth'
    pod 'FacebookCore'
    pod 'FacebookLogin'
  end

end
