# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'myVelib' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myVelib
	pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Amplitude-iOS'
    pod 'Fabric'
    pod 'Crashlytics'
    
  target 'myVelibTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myVelibUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
